package org.glmdb.blueprints.jni;

/**
 * Date: 2013/12/14
 * Time: 1:00 PM
 */
public enum DbEnum {
    VERTEX_DB,
    EDGE_DB,
    VERTEX_PROPERTY_DB,
    EDGE_PROPERTY_DB,
    LABEL_DB,
    CONFIG_DB,
    VERTEX_BOOLEAN_INDEX,
    VERTEX_BYTE_INDEX,
    VERTEX_SHORT_INDEX,
    VERTEX_INT_INDEX,
    VERTEX_LONG_INDEX,
    VERTEX_FLOAT_INDEX,
    VERTEX_DOUBLE_INDEX,
    VERTEX_CHAR_INDEX,
    VERTEX_STRING_INDEX,
    EDGE_BOOLEAN_INDEX,
    EDGE_BYTE_INDEX,
    EDGE_SHORT_INDEX,
    EDGE_INT_INDEX,
    EDGE_LONG_INDEX,
    EDGE_FLOAT_INDEX,
    EDGE_DOUBLE_INDEX,
    EDGE_CHAR_INDEX,
    EDGE_STRING_INDEX
}
